import { Message } from '@/app/types'

export const MOCK_MESSAGES: Message[] = [
  {
    content: 'what traditional houses do you have that are under 2000 sqft?',
    type: 'user',
  },
  {
    calls: [
      {
        id: 'call_lKgx6mCiCxdYUCtWXDHikjHB',
        name: 'searchFloorplans',
        arguments: { mxsqft: 2000, tr: true },
      },
    ],
    content: null,
    type: 'functionCall',
  },
  {
    name: '',
    content: {
      items: [
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '1074-115',
          squareFeet: 1673,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '4',
          bedrooms: 4,
          id: '430-314',
          squareFeet: 1994,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '18-318',
          squareFeet: 920,
          stories: 2,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '1',
          bedrooms: 1,
          id: '1070-120',
          squareFeet: 612,
          stories: 1,
          title: 'Barndominium Photo Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '1074-44',
          squareFeet: 1924,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-209',
          squareFeet: 1416,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '430-316',
          squareFeet: 1797,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-362',
          squareFeet: 1690,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '430-376',
          squareFeet: 1320,
          stories: 1,
          title: 'Barndominium Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '44-236',
          squareFeet: 1611,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '44-224',
          squareFeet: 1035,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '430-264',
          squareFeet: 1956,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '430-256',
          squareFeet: 1448,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-206',
          squareFeet: 1292,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-262',
          squareFeet: 1459,
          stories: 1,
          title: 'Country Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '1',
          bedrooms: 1,
          id: '430-293',
          squareFeet: 525,
          stories: 2,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-253',
          squareFeet: 1493,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '44-247',
          squareFeet: 1500,
          stories: 1,
          title: 'Cottage Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '923-330',
          squareFeet: 1250,
          stories: 1,
          title: 'Cottage Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 4,
          id: '430-286',
          squareFeet: 1998,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '44-263',
          squareFeet: 1425,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '1',
          bedrooms: 1,
          id: '461-99',
          squareFeet: 640,
          stories: 2,
          title: 'Craftsman Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '126-196',
          squareFeet: 1703,
          stories: 2,
          title: 'Craftsman Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '51-1194',
          squareFeet: 1973,
          stories: 2,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '1073-29',
          squareFeet: 1603,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '44-227',
          squareFeet: 1311,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '1',
          bedrooms: 2,
          id: '18-1016',
          squareFeet: 984,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '48-1166',
          squareFeet: 1658,
          stories: 2,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '1',
          bedrooms: 2,
          id: '430-277',
          squareFeet: 960,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-318',
          squareFeet: 1479,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
      ],
    },
    id: 'call_lKgx6mCiCxdYUCtWXDHikjHB',
    type: 'functionResponse',
  },
  {
    content:
      '{"recommendations":[{"ids":["430-314","430-286","126-196","48-1166","1074-115"],"summary":"Here are some charming traditional-style floorplans that are thoughtfully crafted under 2000 sqft, each offering a comfortable and warm ambiance. These designs prioritize space efficiency while providing ample room with their multiple bedrooms and bathrooms, perfect for families or those who love hosting guests. With their classic exterior and functional layouts, these homes invite you into a timeless setting that balances both aesthetic charm and practical living. Consider the story of the house, the number of stories, and external features like porches or garages for even more personalization."}],"opening":"I\'ve found a wonderful selection of traditional houses under 2000 square feet just for you!","nexSteps":"To refine your search further, consider specifying the number of stories, particular features like a basement or bonus room, or even outdoor elements such as porches or decks. What other features might you be interested in?","filter":"{\\"mxsqft\\":2000,\\"tr\\":true}"}',
    type: 'assistant',
  },

  { content: '1 story please', type: 'user' },
  {
    calls: [
      {
        id: 'call_n16PLZW4umJdeTSxUS412hre',
        name: 'searchFloorplans',
        arguments: { mxsqft: 2000, tr: true, s1: true },
      },
    ],
    content: null,
    type: 'functionCall',
  },
  {
    name: '',
    content: {
      items: [
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '1074-115',
          squareFeet: 1673,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '4',
          bedrooms: 4,
          id: '430-314',
          squareFeet: 1994,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '1',
          bedrooms: 1,
          id: '1070-120',
          squareFeet: 612,
          stories: 1,
          title: 'Barndominium Photo Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '1074-44',
          squareFeet: 1924,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-209',
          squareFeet: 1416,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '430-316',
          squareFeet: 1797,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-362',
          squareFeet: 1690,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '430-376',
          squareFeet: 1320,
          stories: 1,
          title: 'Barndominium Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '44-236',
          squareFeet: 1611,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '44-224',
          squareFeet: 1035,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '430-264',
          squareFeet: 1956,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '430-256',
          squareFeet: 1448,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-206',
          squareFeet: 1292,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-262',
          squareFeet: 1459,
          stories: 1,
          title: 'Country Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-253',
          squareFeet: 1493,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '44-247',
          squareFeet: 1500,
          stories: 1,
          title: 'Cottage Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '923-330',
          squareFeet: 1250,
          stories: 1,
          title: 'Cottage Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 4,
          id: '430-286',
          squareFeet: 1998,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '44-263',
          squareFeet: 1425,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '1073-29',
          squareFeet: 1603,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '44-227',
          squareFeet: 1311,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '1',
          bedrooms: 2,
          id: '18-1016',
          squareFeet: 984,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '1',
          bedrooms: 2,
          id: '430-277',
          squareFeet: 960,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-318',
          squareFeet: 1479,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '430-246',
          squareFeet: 1599,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-367',
          squareFeet: 1641,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-214',
          squareFeet: 1817,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '430-282',
          squareFeet: 1064,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '44-245',
          squareFeet: 1120,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-221',
          squareFeet: 1706,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
      ],
    },
    id: 'call_n16PLZW4umJdeTSxUS412hre',
    type: 'functionResponse',
  },
  {
    content:
      '{"recommendations":[{"ids":["430-314","430-286","1074-115","1074-44","44-236"],"summary":"Delight in the elegance of one-story traditional houses that seamlessly infuse charming design and modern livability, all under 2000 sqft. These homes feature generous bedrooms and bathrooms, making them ideal for growing families or those who enjoy having their space. With their single-story layout, they offer ease of mobility and a cozy atmosphere, perfect for enjoying everyday life. Each floorplan is distinct, yet they all capture the timeless appeal and comfort that traditional styles exude. Explore functional layouts with welcoming living spaces, perfect for creating lifelong memories."}],"opening":"I\'ve found a wonderful selection of traditional one-story houses under 2000 square feet just for you!","nexSteps":"Would you like to consider additional features such as a garage, porch, or a specific type of kitchen layout? Let me know if there are other preferences to help narrow down your search.","filter":"{\\"mxsqft\\":2000,\\"tr\\":true,\\"s1\\":true}"}',
    type: 'assistant',
  },

  { content: 'any with 2-car garages?', type: 'user' },
  {
    calls: [
      {
        id: 'call_JI6qxtYV8YsVoNZIsxqo59S0',
        name: 'searchFloorplans',
        arguments: { mxsqft: 2000, tr: true, s1: true, g2: true },
      },
    ],
    content: null,
    type: 'functionCall',
  },
  {
    name: '',
    content: {
      items: [
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '1074-115',
          squareFeet: 1673,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '1',
          bedrooms: 1,
          id: '1070-120',
          squareFeet: 612,
          stories: 1,
          title: 'Barndominium Photo Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '1074-44',
          squareFeet: 1924,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-209',
          squareFeet: 1416,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-362',
          squareFeet: 1690,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '44-236',
          squareFeet: 1611,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '430-264',
          squareFeet: 1956,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-262',
          squareFeet: 1459,
          stories: 1,
          title: 'Country Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-253',
          squareFeet: 1493,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 4,
          id: '430-286',
          squareFeet: 1998,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '1',
          bedrooms: 2,
          id: '18-1016',
          squareFeet: 984,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-318',
          squareFeet: 1479,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '430-246',
          squareFeet: 1599,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-367',
          squareFeet: 1641,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-214',
          squareFeet: 1817,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-221',
          squareFeet: 1706,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '923-253',
          squareFeet: 1591,
          stories: 1,
          title: 'Cottage Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '1074-47',
          squareFeet: 1650,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '923-250',
          squareFeet: 1596,
          stories: 1,
          title: 'Barndominium Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 4,
          id: '65-291',
          squareFeet: 1601,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '17-1044',
          squareFeet: 1382,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '44-274',
          squareFeet: 1500,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '430-369',
          squareFeet: 1094,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-89',
          squareFeet: 1842,
          stories: 1,
          title: 'European Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '1073-15',
          squareFeet: 1419,
          stories: 1,
          title: 'Craftsman Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '18-1055',
          squareFeet: 1096,
          stories: 1,
          title: 'Ranch Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '430-252',
          squareFeet: 1998,
          stories: 1,
          title: 'Ranch Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '430-284',
          squareFeet: 1828,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '21-463',
          squareFeet: 1416,
          stories: 1,
          title: 'Country Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '430-213',
          squareFeet: 1327,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
      ],
    },
    id: 'call_JI6qxtYV8YsVoNZIsxqo59S0',
    type: 'functionResponse',
  },
  {
    content:
      '{"recommendations":[{"ids":["1074-115","430-346","430-252","44-236","430-209"],"summary":"Here you have a selection of delightful one-story traditional homes, each with the added convenience of a two-car garage. These floorplans provide a blend of classic charm and modern practicality, without sacrificing the cozy, intimate feel that one-story homes offer. With their ample bedrooms and bath configurations, they\'re designed for both comfort and functionality. The traditional style ensures timeless appeal, making it perfect for families or those who love welcoming guests. Imagine pulling into your spacious garage and entering a home that embodies warmth and efficiency."}],"opening":"I\'ve found a wonderful selection of traditional one-story houses with 2-car garages for you!","nexSteps":"Would you like to explore any specific interior features like open floor plans, a dedicated office space, or anything else to make the experience truly yours? Let me know!","filter":"{\\"mxsqft\\":2000,\\"tr\\":true,\\"s1\\":true,\\"g2\\":true}"}',
    type: 'assistant',
  },
]
