import { Message } from '@/app/types'

export const MOCK_MESSAGES: Message[] = [
  {
    content: 'what traditional houses do you have that are under 2000 sqft?',
    type: 'user',
  },
  {
    calls: [
      {
        id: 'call_2IYVwh7OLMHC5mCWhfKt0ebY',
        name: 'searchFloorplans',
        arguments: {
          tr: true,
          mxsqft: 2000,
        },
      },
    ],
    content: null,
    type: 'functionCall',
  },
  {
    name: '',
    content: {
      items: [
        {
          bathrooms: '1',
          bedrooms: 1,
          id: '::1070-120::',
          squareFeet: 612,
          stories: 1,
          title: 'Barndominium Photo Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::44-274::',
          squareFeet: 1500,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '::430-316::',
          squareFeet: 1797,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-362::',
          squareFeet: 1690,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '::1074-44::',
          squareFeet: 1924,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '::430-282::',
          squareFeet: 1064,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::44-236::',
          squareFeet: 1611,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::44-224::',
          squareFeet: 1035,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '::430-246::',
          squareFeet: 1599,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '1',
          bedrooms: 1,
          id: '::430-293::',
          squareFeet: 525,
          stories: 2,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-209::',
          squareFeet: 1416,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '::430-256::',
          squareFeet: 1448,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-318::',
          squareFeet: 1479,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-221::',
          squareFeet: 1706,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '::430-264::',
          squareFeet: 1956,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::923-234::',
          squareFeet: 1500,
          stories: 1,
          title: 'Barndominium Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-262::',
          squareFeet: 1459,
          stories: 1,
          title: 'Country Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::44-247::',
          squareFeet: 1500,
          stories: 1,
          title: 'Cottage Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '4',
          bedrooms: 4,
          id: '::430-314::',
          squareFeet: 1994,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '::430-60::',
          squareFeet: 1800,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::923-330::',
          squareFeet: 1250,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-110::',
          squareFeet: 1884,
          stories: 1,
          title: 'European Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-206::',
          squareFeet: 1292,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-253::',
          squareFeet: 1493,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::44-227::',
          squareFeet: 1311,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '::48-1029::',
          squareFeet: 1285,
          stories: 1,
          title: 'Cottage Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '::18-318::',
          squareFeet: 920,
          stories: 2,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '1',
          bedrooms: 2,
          id: '::430-277::',
          squareFeet: 960,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '::44-245::',
          squareFeet: 1120,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::44-263::',
          squareFeet: 1425,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
      ],
    },
    id: 'call_2IYVwh7OLMHC5mCWhfKt0ebY',
    type: 'functionResponse',
  },
  {
    content:
      "Here are some charming traditional houses that you might love, all under 2000 sqft:\n\n1. **id**: _::44-236:: - **Traditional Exterior - Front Elevation Plan** (3 Bedrooms, 2 Bathrooms, 1611 sqft, 1 Story)\n2. **id**: _::923-330:: - **Traditional Exterior - Front Elevation Plan** (3 Bedrooms, 2 Bathrooms, 1250 sqft, 1 Story)\n3. **id**: _::44-245:: - **Traditional Exterior - Front Elevation Plan** (2 Bedrooms, 2 Bathrooms, 1120 sqft, 1 Story)\n4. **id**: _::18-318:: - **Traditional Exterior - Front Elevation Plan** (2 Bedrooms, 2 Bathrooms, 920 sqft, 2 Stories)\n5. **id**: _::430-264:: - **Farmhouse Exterior - Front Elevation Plan** (3 Bedrooms, 2.5 Bathrooms, 1956 sqft, 1 Story)\n\nThese floorplans offer delightful architectural styles and provide an excellent balance of space and comfort. Whether you’re looking for something cozy or a bit more spacious, there’s a great variety here! \n\nAs you continue your search, consider other features such as garage space, kitchen layout, and outdoor areas that could complement your lifestyle. Let me know if you'd like more options or more specific features!",
    type: 'assistant',
  },
  {
    content: '1 story only please',
    type: 'user',
  },
  {
    calls: [
      {
        id: 'call_Z7GeXotsiARPE0M1bzHd8OW4',
        name: 'searchFloorplans',
        arguments: {
          tr: true,
          mxsqft: 2000,
          s1: true,
        },
      },
    ],
    content: null,
    type: 'functionCall',
  },
  {
    name: '',
    content: {
      items: [
        {
          bathrooms: '1',
          bedrooms: 1,
          id: '::1070-120::',
          squareFeet: 612,
          stories: 1,
          title: 'Barndominium Photo Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::44-274::',
          squareFeet: 1500,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '::430-316::',
          squareFeet: 1797,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-362::',
          squareFeet: 1690,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '::1074-44::',
          squareFeet: 1924,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '::430-282::',
          squareFeet: 1064,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::44-236::',
          squareFeet: 1611,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::44-224::',
          squareFeet: 1035,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '::430-246::',
          squareFeet: 1599,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-209::',
          squareFeet: 1416,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '::430-256::',
          squareFeet: 1448,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-318::',
          squareFeet: 1479,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-221::',
          squareFeet: 1706,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '::430-264::',
          squareFeet: 1956,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::923-234::',
          squareFeet: 1500,
          stories: 1,
          title: 'Barndominium Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-262::',
          squareFeet: 1459,
          stories: 1,
          title: 'Country Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::44-247::',
          squareFeet: 1500,
          stories: 1,
          title: 'Cottage Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '4',
          bedrooms: 4,
          id: '::430-314::',
          squareFeet: 1994,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '::430-60::',
          squareFeet: 1800,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::923-330::',
          squareFeet: 1250,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-110::',
          squareFeet: 1884,
          stories: 1,
          title: 'European Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-206::',
          squareFeet: 1292,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-253::',
          squareFeet: 1493,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::44-227::',
          squareFeet: 1311,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '::48-1029::',
          squareFeet: 1285,
          stories: 1,
          title: 'Cottage Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '1',
          bedrooms: 2,
          id: '::430-277::',
          squareFeet: 960,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '::44-245::',
          squareFeet: 1120,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::44-263::',
          squareFeet: 1425,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::427-6::',
          squareFeet: 1924,
          stories: 1,
          title: 'Ranch Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-241::',
          squareFeet: 1740,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
      ],
    },
    id: 'call_Z7GeXotsiARPE0M1bzHd8OW4',
    type: 'functionResponse',
  },
  {
    content:
      'Here are some fabulous traditional houses that are all 1 story and under 2000 sqft:\n\n1. **id**: _::44-236:: - **Traditional Exterior - Front Elevation Plan** (3 Bedrooms, 2 Bathrooms, 1611 sqft)\n2. **id**: _::923-330:: - **Traditional Exterior - Front Elevation Plan** (3 Bedrooms, 2 Bathrooms, 1250 sqft)\n3. **id**: _::44-245:: - **Traditional Exterior - Front Elevation Plan** (2 Bedrooms, 2 Bathrooms, 1120 sqft)\n4. **id**: _::430-262:: - **Country Exterior - Front Elevation Plan** (3 Bedrooms, 2 Bathrooms, 1459 sqft)\n5. **id**: _::44-263:: - **Farmhouse Exterior - Front Elevation Plan** (3 Bedrooms, 2 Bathrooms, 1425 sqft)\n\nThese options provide a great blend of style and convenience, making them perfect for easy living! Each floorplan has its unique charm while ensuring ample space for relaxation and family gatherings. \n\nIf you have specific features or styles in mind, let me know, and I can help you find even more tailored options!',
    type: 'assistant',
  },
  {
    content: 'any with 2-car garages?',
    type: 'user',
  },
  {
    calls: [
      {
        id: 'call_UaGfJNqOAi0EW866W490PYxU',
        name: 'searchFloorplans',
        arguments: {
          tr: true,
          mxsqft: 2000,
          s1: true,
          g2: true,
        },
      },
    ],
    content: null,
    type: 'functionCall',
  },
  {
    name: '',
    content: {
      items: [
        {
          bathrooms: '1',
          bedrooms: 1,
          id: '::1070-120::',
          squareFeet: 612,
          stories: 1,
          title: 'Barndominium Photo Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::44-274::',
          squareFeet: 1500,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-362::',
          squareFeet: 1690,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '::1074-44::',
          squareFeet: 1924,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::44-236::',
          squareFeet: 1611,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '::430-246::',
          squareFeet: 1599,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-209::',
          squareFeet: 1416,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-318::',
          squareFeet: 1479,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-221::',
          squareFeet: 1706,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '::430-264::',
          squareFeet: 1956,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-262::',
          squareFeet: 1459,
          stories: 1,
          title: 'Country Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '::430-60::',
          squareFeet: 1800,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-110::',
          squareFeet: 1884,
          stories: 1,
          title: 'European Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-253::',
          squareFeet: 1493,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::427-6::',
          squareFeet: 1924,
          stories: 1,
          title: 'Ranch Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-241::',
          squareFeet: 1740,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::44-256::',
          squareFeet: 1629,
          stories: 1,
          title: 'Country Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::21-463::',
          squareFeet: 1416,
          stories: 1,
          title: 'Country Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::430-214::',
          squareFeet: 1817,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 4,
          id: '::430-286::',
          squareFeet: 1998,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 4,
          id: '::430-93::',
          squareFeet: 1798,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::923-253::',
          squareFeet: 1591,
          stories: 1,
          title: 'Cottage Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 4,
          id: '::430-335::',
          squareFeet: 1700,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::923-250::',
          squareFeet: 1596,
          stories: 1,
          title: 'Barndominium Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::17-1044::',
          squareFeet: 1382,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '::1070-170::',
          squareFeet: 1248,
          stories: 1,
          title: 'Farmhouse Photo Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 2,
          id: '::430-239::',
          squareFeet: 1301,
          stories: 1,
          title: 'Country Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2',
          bedrooms: 3,
          id: '::20-2352::',
          squareFeet: 1176,
          stories: 1,
          title: 'Traditional Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 2,
          id: '::1073-41::',
          squareFeet: 1726,
          stories: 1,
          title: 'Ranch Exterior - Front Elevation Plan',
        },
        {
          bathrooms: '2.5',
          bedrooms: 3,
          id: '::1074-47::',
          squareFeet: 1650,
          stories: 1,
          title: 'Farmhouse Exterior - Front Elevation Plan',
        },
      ],
    },
    id: 'call_UaGfJNqOAi0EW866W490PYxU',
    type: 'functionResponse',
  },
  {
    content:
      "Here are some fantastic one-story traditional houses with 2-car garages, all under 2000 sqft:\n\n1. **id**: _::430-286:: - **Traditional Exterior - Front Elevation Plan** (4 Bedrooms, 2.5 Bathrooms, 1998 sqft)\n2. **id**: _::430-93:: - **Traditional Exterior - Front Elevation Plan** (4 Bedrooms, 2 Bathrooms, 1798 sqft)\n3. **id**: _::430-214:: - **Traditional Exterior - Front Elevation Plan** (3 Bedrooms, 2 Bathrooms, 1817 sqft)\n4. **id**: _::430-335:: - **Farmhouse Exterior - Front Elevation Plan** (4 Bedrooms, 2 Bathrooms, 1700 sqft)\n5. **id**: _::430-60:: - **Traditional Exterior - Front Elevation Plan** (3 Bedrooms, 2.5 Bathrooms, 1800 sqft)\n\nThese homes combine elegance and functionality with the added bonus of garage space for convenience! Think of all the possibilities - whether it's for cars, storage, or even a workshop! \n\nIf you have any more specific needs or features you'd like to explore, let me know, and I'm here to assist!",
    type: 'assistant',
  },
]
